<?php

use Illuminate\Database\Seeder;

class CarreraMateriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Quimica
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'1',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'2',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'3',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'4',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'5',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'6',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'7',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'8',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'9',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'10',  
        ]);

        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'11',  
        ]);

        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'12',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'13',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'14',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'15',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'16',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'17',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'18',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'2',
              'materia_id'=>'19',  
        ]);

        //Alimentos
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'20',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'21',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'22',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'23',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'24',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'25',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'26',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'27',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'28',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'29',  
        ]);
        
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'30',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'31',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'32',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'33',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'34',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'34',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'35',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'36',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'37',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'38',  
        ]);
        DB::table('carrera_materia')->insert([
              'carrera_id'=>'1',
              'materia_id'=>'39',  
        ]);

   }
}
